name: venv
channels:
  - conda-forge
  - pytorch

dependencies:
  # core
  - python==3.6
  - pytorch==1.4.0
  # utils
  - tensorboard==2.0.0
  - torchvision==0.5.0
  - opencv==4.1.2
  - pandas==1.0.3
  - scikit-image==0.16.2
  - requests==2.23.0
  - pip:
    - pytorch-lightning==0.7.1
    - torchxrayvision==0.0.3
    - git+https://github.com/kornia/kornia.git
